version: "3"


services:
  nginx:
    image: nginx
    hostname: nginx
    volumes:
      - ${WORKDIR}:/var/www/qlikbeton:rw
      - ./nginx/conf.d/qlikbeton.conf:/etc/nginx/conf.d/qlikbeton.conf:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/htpasswd:/etc/nginx/htpasswd:rw
      - ./nginx/log:/var/log/nginx:rw
    links:
      - php
    ports:
      - 80:80
    networks:
      - front-tier
      - back-tier
    restart: always
networks:
  webnet:
